server:
  port: 9090
  servlet:
    context-path: /security


spring:
  security:
    user:
      name: admin
      password: admin
      roles: admin, manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password: root
jpa:
    hibernate:
      ddl-auto: update
